spring.application.name=shoppingcart

# Database connection
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# Disable spring-boot starting banner
spring.main.banner-mode=off

# Logging level
logging.level.root=WARN
logging.level.org.springframework.web=WARN

# Show JPA/Hibernate logging messages
#logging.level.org.hibernate.SQL=trace
#logging.level.org.hibernate.orm.jdbc.bind=trace

# Openapi/Springdoc config
springdoc.packages-to-scan=com.example.shoppingcart

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shoppingcart@gmail.com
spring.mail.password=wkyhhbuejlmsuvdv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CORS configuration
cors.allowed-origins=http://localhost:3000
cors.allowed-methods=GET,POST,PUT,DELETE
cors.allowed-headers=*
